#!/bin/sh
set -efu

flake8 setup.py

# create a known-bad file
cat << EOF > $ADTTMP/test.py
import sys  # unused import

print('Hello world, this is an overly long line for PEP-8. We expect flake8 to complain')
# undeclared variable
count += 1
EOF
set +e
flake8 $ADTTMP/test.py > $ADTTMP/out
RC=$?
set -e
echo 'flake8 output on known-bad file:'
cat $ADTTMP/out

if [ $RC -eq 0 ]; then
   echo "flake8 expected to fail, but it succeeded:" >&2
   exit 1
fi

grep -q 'F401.*sys' $ADTTMP/out
grep -q 'E501.*line too long' $ADTTMP/out
grep -q 'F821.*count' $ADTTMP/out
